# 
# Officaial Tips
# https://yazi-rs.github.io/docs/tips/#smart-enter
 
# - Dropping to the shell
[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# - Close input by once Esc press
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

# - Smart Enter
[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# - Smart Paste
[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

# cd back to the root of the current Git repository
[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

# Toggle Preview pane
# keymap.toml
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

# macOS: Preview files with the system Quick Look
[[mgr.prepend_keymap]]
on = "P"
run = "shell -- qlmanage -p %s"
